### ISSUE TITLE
Problems getting example to run

### ISSUE THREAD

**Issue by elnappo** [wanduow/lpicollector#1]
I have a few problems getting the examples to run. At first I need to run lpi_collector with `LD_LIBRARY_PATH="/usr/local/lib;$LD_LIBRARY_PATH" /usr/local/bin/lpi_collector -r 10 int:eth0` under Ubuntu 16.04, while e.g. lpi_protoident is running fine. I compiled lpicollector out of the repository.
After connecting simple_flow_reporter.py I don't get any output. Is lpicollector still supported (last commit was one year ago)? 

```
$ ldd /usr/local/bin/lpi_collector
   linux-vdso.so.1 =>  (0x00007ffe84b3f000)
   libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8756dcf000)
   libfifo.so.1 => not found
   libwandevent.so.3 => not found
   libflowmanager.so.2 => not found
   libprotoident.so.2 => not found
   libtrace.so.3 => /usr/lib/libtrace.so.3 (0x00007f8756bb0000)
   libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f875682e000)
   libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8756465000)
   /lib64/ld-linux-x86-64.so.2 (0x0000559087d62000)
   libwandio.so.1 => /usr/lib/libwandio.so.1 (0x00007f875625d000)
   libpcap.so.0.8 => /usr/lib/x86_64-linux-gnu/libpcap.so.0.8 (0x00007f875601b000)
   libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8755d12000)
   libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8755afb000)
   libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f87558eb000)
   libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f87556d1000)
   liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f87554ae000)
   libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f87552aa000)

ldd /usr/local/bin/lpi_protoident
    linux-vdso.so.1 =>  (0x00007ffd2e193000)
    libprotoident.so.2 => /usr/local//lib/libprotoident.so.2 (0x00007f24ea44d000)
    libflowmanager.so.2 => /usr/local//lib/libflowmanager.so.2 (0x00007f24ea246000)
    libtrace.so.3 => /usr/lib/libtrace.so.3 (0x00007f24ea021000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f24e9c9f000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f24e98d6000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f24e96bf000)
    libwandio.so.1 => /usr/lib/libwandio.so.1 (0x00007f24e94b8000)
    libpcap.so.0.8 => /usr/lib/x86_64-linux-gnu/libpcap.so.0.8 (0x00007f24e9276000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f24e8f6c000)
    /lib64/ld-linux-x86-64.so.2 (0x0000561205fb4000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f24e8d4f000)
    libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f24e8b3f000)
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f24e8924000)
    liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f24e8702000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f24e84fe000)
```

**Comment by salcock** [comment]
Yes, the collector is still supported. We're not actively working on it at the moment but I'm happy to fix any bugs and answer any questions that crop up :)

By default, the collector won't do flow reporting as this is a somewhat experimental feature. You can enable and configure flow reporting by passing the following CLI options to lpi_collector:
  -E, -O : enable reporting of expired and ongoing flows, respectively 
  -e <interval> : determines the frequency at which expired flows are reported to clients.
  -v <interval> : determines the frequency at which ongoing flows are reported to clients.
  -o <interval> : only flows that have existed for this number of seconds will be classified as ongoing (to avoid the clients being hammered if you see a port scan or some similar burst of flows).

If you're more interested in the aggregate statistics that lpi_collector is designed for, the lpi.py script would be a better example to play around with.

**Comment by elnappo** [comment]
Thank you! I ran lpi_collector with `LD_LIBRARY_PATH="/usr/local/lib;$LD_LIBRARY_PATH" /usr/local/bin/lpi_collector -r 10 -E -O -e 10 -v 10 int:eth0`. lpi.py exited with the following traceback:

```
Traceback (most recent call last):
  File "lpi.py", line 40, in <module>
    type, stats = lpicol.read_lpicp(s)
  File "/root/lpicollector/exampleclients/common.py", line 210, in read_lpicp
    stats = parse_expired_record(msg_buf, name_len)
NameError: global name 'parse_expired_record' is not defined
```

there seems to be no function called `parse_expired_record` in common.py

**Comment by salcock** [comment]
I've pushed a fix for this to the master branch. parse_flow_record() should
have been called instead of parse_expired_record().

Thanks for reporting the bug :)
